name: BuildPlugin
version: 1.0
main: de.CypDasHuhn.Build.main.Main
api-version: '1.20'

commands:
  test:
    description: w
  setstructure:
    description: w
  buildsave:
    aliases: bs
  switchworld:
    aliases: sw